version: '3.9'

networks:
  tt_test_net:
  traefik_proxy_network:
     external: true

services:
  db:
    image: mysql:8
    container_name: tt_test_db
    labels:
      - docker-volume-backup.archive-pre=/bin/sh -c '/usr/bin/mysqldump -uroot -pQMPDIw9ZbOqb27mkn928+9e5ArOMC3dA tt > /tmp/file_storage/tt.sql'
    restart: always
    #    ports:
    #      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - file_storage_test:/tmp/file_storage

    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      #      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=tt
      - MYSQL_PASSWORD=${MYSQL_TT_PASSWORD}
      - MYSQL_DATABASE=tt
    networks:
      - tt_test_net

  yarn:
    image: node:16.13.0
    container_name: tt_test_yarn
    depends_on:
      - db
    expose:
      - "3000"
    volumes:
      - ./src:/var/www/html
      - file_storage_test:/var/www/file_storage
    working_dir: /var/www/html
    entrypoint: ['yarn']
    environment:
      - TZ=Europe/Moscow
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.www-redirect.redirectregex.regex=^(https?://)www.(.*)$$"
      - "traefik.http.middlewares.www-redirect.redirectregex.replacement=$${1}$${2}"
      - "traefik.http.middlewares.www-redirect.redirectregex.permanent=true"
      - "traefik.http.routers.tt_test.rule=Host(`test.superduperbilet.site`) || Host(`www.test.superduperbilet.site`)"
      # - "traefik.http.routers.tt_test.rule=Host(`test.superduperbilet.site`)"
      - "traefik.http.routers.tt_test.entrypoints=websecure"
      - "traefik.http.routers.tt_test.tls.certresolver=myresolver"
      - "traefik.http.routers.tt_test.middlewares=www-redirect"
      - "traefik.docker.network=traefik_proxy_network"
    networks:
      - tt_test_net
      - traefik_proxy_network

volumes:
  file_storage_test:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${PWD}/file_storage