version: '3.9'

networks:
  tt_prod_net:
  traefik_proxy_network:
     external: true

services:
  db:
    image: mysql:8
    container_name: tt_prod_db
    labels:
      - docker-volume-backup.archive-pre=/bin/sh -c '/usr/bin/mysqldump -uroot -p${MYSQL_ROOT_PASSWORD} tt > /tmp/file_storage/tt.sql'
    restart: always
    #    ports:
    #      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql-files:/var/lib/mysql-files
      - file_storage:/tmp/file_storage

    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      #      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=tt
      - MYSQL_PASSWORD=${MYSQL_TT_PASSWORD}
      - MYSQL_DATABASE=tt
    networks:
      - tt_prod_net

  yarn:
    image: node:16.13.0
    container_name: tt_prod_yarn
    depends_on:
      - db
    expose:
      - "3000"
    volumes:
      - ./src:/var/www/html
      - file_storage:/var/www/file_storage
    working_dir: /var/www/html
    entrypoint: ['yarn']
    command: "start"
    restart: always
    environment:
      - TZ=Europe/Moscow
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.www-redirect.redirectregex.regex=^(https?://)www.(.*)$$"
      - "traefik.http.middlewares.www-redirect.redirectregex.replacement=$${1}$${2}"
      - "traefik.http.middlewares.www-redirect.redirectregex.permanent=true"
      - "traefik.http.routers.tt_prod.rule=Host(`ticket.otaku.ru`) || Host(`www.ticket.otaku.ru`)"
      - "traefik.http.routers.tt_prod.entrypoints=websecure"
      - "traefik.http.routers.tt_prod.tls.certresolver=myresolver"
      - "traefik.http.routers.tt_prod.middlewares=www-redirect"
      - "traefik.docker.network=traefik_proxy_network"

    networks:
      - tt_prod_net
      - traefik_proxy_network

  backup:
    # In production, it is advised to lock your image tag to a proper
    # release version instead of using `latest`.
    # Check https://github.com/offen/docker-volume-backup/releases
    # for a list of available releases.
    image: offen/docker-volume-backup:v2.20.0
    container_name: tt_prod_backup
    restart: always
    environment:
      BACKUP_FILENAME: backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_PRUNING_PREFIX: backup-
      BACKUP_RETENTION_DAYS: 7
    #    env_file: ./backup.env # see below for configuration reference
    networks:
      - tt_prod_net
    volumes:
      - file_storage:/backup/tt:ro
      # Mounting the Docker socket allows the script to stop and restart
      # the container during backup. You can omit this if you don't want
      # to stop the container. In case you need to proxy the socket, you can
      # also provide a location by setting `DOCKER_HOST` in the container
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # If you mount a local directory or volume to `/archive` a local
      # copy of the backup will be stored there. You can override the
      # location inside of the container by setting `BACKUP_ARCHIVE`.
      # You can omit this if you do not want to keep local backups.
      - ./backups:/archive

volumes:
  file_storage:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${PWD}/file_storage