import { PriceRange } from "@prisma/client"

type HallTicket = {
    number: number,
    priceRange?: PriceRange 
}
export type HallTicketRow = { number: number, tickets: HallTicket[] }

export default function getHall(priceRange: PriceRange[]): HallTicketRow[] {
    return [
        {
            number: 1,
            tickets: [
                { number: 1 },
                { number: 2 },
                { number: 3 },
                { number: 4 },
                { number: 5 },
                { number: 6 },
                { number: 7 },
                { number: 8 },
                { number: 9 },
                { number: 10 },
                { number: 11 },
                { number: 12 },
                { number: 13 },
                { number: 14 },
                { number: 15 },
                { number: 16 },
                { number: 17 },
                { number: 18 },
                { number: 19 },
                { number: 20 },
                { number: 21 }                
            ]
        },
        {
            number: 2,
            tickets: [
                { number: 1 },
                { number: 2 },
                { number: 3, priceRange: priceRange[1] },
                { number: 4, priceRange: priceRange[1] },
                { number: 5 },
                { number: 6 },
                { number: 7 },
                { number: 8 },
                { number: 9 },
                { number: 10 },
                { number: 11 },
                { number: 12 },
                { number: 13 },
                { number: 14 },
                { number: 15 },
                { number: 16 },
                { number: 17 },
                { number: 18 },
                { number: 19, priceRange: priceRange[1] },
                { number: 20, priceRange: priceRange[1] },
                { number: 21, priceRange: priceRange[1] },
                { number: 22, priceRange: priceRange[1] }
            ]
        },
        {
            number: 3,
            tickets: [
                { number: 1 },
                { number: 2 },
                { number: 3 },
                { number: 4 },
                { number: 5 },
                { number: 6 },
                { number: 7 },
                { number: 8 },
                { number: 9 },
                { number: 10 },
                { number: 11 },
                { number: 12 },
                { number: 13 },
                { number: 14 },
                { number: 15 },
                { number: 16 },
                { number: 17 },
                { number: 18 },
                { number: 19 },
                { number: 20 },
                { number: 21 },
                { number: 22 },
                { number: 23 }
            ]
        },
        {
            number: 4,
            tickets: [
                { number: 1 },
                { number: 2, priceRange: priceRange[0] },
                { number: 3, priceRange: priceRange[1] },
                { number: 4, priceRange: priceRange[1] },
                { number: 5, priceRange: priceRange[1] },
                { number: 6, priceRange: priceRange[1] },
                { number: 7 },
                { number: 8 },
                { number: 9 },
                { number: 10 },
                { number: 11 },
                { number: 12 },
                { number: 13 },
                { number: 14 },
                { number: 15 },
                { number: 16 },
                { number: 17 },
                { number: 18 },
                { number: 19 },
                { number: 20 },
                { number: 21, priceRange: priceRange[1] },
                { number: 22, priceRange: priceRange[1] },
                { number: 23, priceRange: priceRange[1] },
                { number: 24, priceRange: priceRange[0] },
                { number: 25, priceRange: priceRange[0] },
            ]
        },
        {
            number: 5,
            tickets: [
                { number: 1 },
                { number: 2 },
                { number: 3 },
                { number: 4 },
                { number: 5 },
                { number: 6 },
                { number: 7 },
                { number: 8 },
                { number: 9 },
                { number: 10 },
                { number: 11 },
                { number: 12 },
                { number: 13 },
                { number: 14 },
                { number: 15 },
                { number: 16 },
                { number: 17 },
                { number: 18 },
                { number: 19 },
                { number: 20 },
                { number: 21 },
                { number: 22 },
                { number: 23 },
                { number: 24 },
                { number: 25 },
                { number: 26 }
            ]
        },
        {
            number: 6,
            tickets: [
                { number: 1, priceRange: priceRange[0] },
                { number: 2, priceRange: priceRange[0] },
                { number: 3, priceRange: priceRange[0] },
                { number: 4, priceRange: priceRange[1] },
                { number: 5, priceRange: priceRange[1] },
                { number: 6, priceRange: priceRange[1] },
                { number: 7, priceRange: priceRange[1] },
                { number: 8, priceRange: priceRange[1] },
                { number: 9, priceRange: priceRange[1] },
                { number: 10, priceRange: priceRange[1] },
                { number: 11, priceRange: priceRange[1] },
                { number: 12, priceRange: priceRange[1] },
                { number: 13, priceRange: priceRange[1] },
                { number: 14, priceRange: priceRange[1] },
                { number: 15, priceRange: priceRange[1] },
                { number: 16, priceRange: priceRange[1] },
                { number: 17, priceRange: priceRange[1] },
                { number: 18, priceRange: priceRange[1] },
                { number: 19, priceRange: priceRange[1] },
                { number: 20, priceRange: priceRange[1] },
                { number: 21, priceRange: priceRange[1] },
                { number: 22, priceRange: priceRange[1] },
                { number: 23, priceRange: priceRange[1] },
                { number: 24, priceRange: priceRange[1] },
                { number: 25, priceRange: priceRange[0] },
                { number: 26, priceRange: priceRange[0] },
                { number: 27, priceRange: priceRange[0] }
            ]
        },
        {
            number: 7,
            tickets: [
                { number: 1 },
                { number: 2 },
                { number: 3 },
                { number: 4 },
                { number: 5 },
                { number: 6 },
                { number: 7 },
                { number: 8 },
                { number: 9 },
                { number: 10 },
                { number: 11 },
                { number: 12 },
                { number: 13 },
                { number: 14 },
                { number: 15 },
                { number: 16 },
                { number: 17 },
                { number: 18 },
                { number: 19 },
                { number: 20 },
                { number: 21 },
                { number: 22 },
                { number: 23 },
                { number: 24 },
                { number: 25 },
                { number: 26 },
                { number: 27 }
            ]
        },
        {
            number: 8,
            tickets: [
                { number: 1, priceRange: priceRange[0] },
                { number: 2, priceRange: priceRange[0] },
                { number: 3, priceRange: priceRange[0] },
                { number: 4, priceRange: priceRange[1] },
                { number: 5, priceRange: priceRange[1] },
                { number: 6, priceRange: priceRange[1] },
                { number: 7, priceRange: priceRange[1] },
                { number: 8, priceRange: priceRange[1] },
                { number: 9, priceRange: priceRange[1] },
                { number: 10, priceRange: priceRange[1] },
                { number: 11, priceRange: priceRange[1] },
                { number: 12 },
                { number: 13 },
                { number: 14 },
                { number: 15 },
                { number: 16, priceRange: priceRange[1] },
                { number: 17, priceRange: priceRange[1] },
                { number: 18, priceRange: priceRange[1] },
                { number: 19, priceRange: priceRange[1] },
                { number: 20, priceRange: priceRange[1] },
                { number: 21, priceRange: priceRange[1] },
                { number: 22, priceRange: priceRange[1] },
                { number: 23, priceRange: priceRange[1] },
                { number: 24, priceRange: priceRange[1] },
                { number: 25, priceRange: priceRange[0] },
                { number: 26, priceRange: priceRange[0] },
                { number: 27, priceRange: priceRange[0] }
            ]
        },
        {
            number: 9,
            tickets: [
                { number: 1 },
                { number: 2 },
                { number: 3 },
                { number: 4 },
                { number: 5 },
                { number: 6 },
                { number: 7 },
                { number: 8 },
                { number: 9 },
                { number: 10 },
                { number: 11 },
                { number: 12 },
                { number: 13 },
                { number: 14 },
                { number: 15 },
                { number: 16 },
                { number: 17 },
                { number: 18 },
                { number: 19 },
                { number: 20 },
                { number: 21 },
                { number: 22 },
                { number: 23 },
                { number: 24 },
                { number: 25 },
                { number: 26 },
                { number: 27 }
            ]
        },
        {
            number: 10,
            tickets: [
                { number: 1 },
                { number: 2 },
                { number: 3 },
                { number: 4 },
                { number: 5 },
                { number: 6 },
                { number: 7 },
                { number: 8 },
                { number: 9 },
                { number: 10 },
                { number: 11 },
                { number: 12 },
                { number: 13 },
                { number: 14 },
                { number: 15 },
                { number: 16 },
                { number: 17 },
                { number: 18 },
                { number: 19 },
                { number: 20 },
                { number: 21 },
                { number: 22 },
                { number: 23 },
                { number: 24 },
                { number: 25 },
                { number: 26 },
                { number: 27 },
                { number: 28 }
            ]
        },
        {
            number: 11,
            tickets: [
                { number: 1 },
                { number: 2 },
                { number: 3 },
                { number: 4 },
                { number: 5 },
                { number: 6 },
                { number: 7 },
                { number: 8 },
                { number: 9 },
                { number: 10 },
                { number: 11 },
                { number: 12 },
                { number: 13 },
                { number: 14 },
                { number: 15 },
                { number: 16 },
                { number: 17 },
                { number: 18 },
                { number: 19 },
                { number: 20 },
                { number: 21 },
                { number: 22 },
                { number: 23 },
                { number: 24 },
                { number: 25 },
                { number: 26 },
                { number: 27 },
                { number: 28 }
            ]
        },
        {
            number: 12,
            tickets: [
                { number: 1 },
                { number: 2 },
                { number: 3 },
                { number: 4 },
                { number: 5 },
                { number: 6 },
                { number: 7 },
                { number: 8 },
                { number: 9 },
                { number: 10 },
                { number: 11 },
                { number: 12 },
                { number: 13 },
                { number: 14 },
                { number: 15 },
                { number: 16 },
                { number: 17 },
                { number: 18 },
                { number: 19 },
                { number: 20 },
                { number: 21 },
                { number: 22 },
                { number: 23 },
                { number: 24 },
                { number: 25 },
                { number: 26 },
                { number: 27 },
                { number: 28 }
            ]
        },
        {
            number: 13,
            tickets: [
                { number: 1 },
                { number: 2 },
                { number: 3 },
                { number: 4 },
                { number: 5 },
                { number: 6 },
                { number: 7 },
                { number: 8 },
                { number: 9 },
                { number: 10 },
                { number: 11 },
                { number: 12 },
                { number: 13 },
                { number: 14 },
                { number: 15 },
                { number: 16 },
                { number: 17 },
                { number: 18 },
                { number: 19 },
                { number: 20 },
                { number: 21 },
                { number: 22 },
                { number: 23 },
                { number: 24 },
                { number: 25 },
                { number: 26 },
                { number: 27 },
                { number: 28 }
            ]
        },
        {
            number: 14,
            tickets: [
                { number: 1 },
                { number: 2 },
                { number: 3 },
                { number: 4 },
                { number: 5 },
                { number: 6 },
                { number: 7 },
                { number: 8 },
                { number: 9 },
                { number: 10 },
                { number: 11 },
                { number: 12 },
                { number: 13 },
                { number: 14 },
                { number: 15 },
                { number: 16 },
                { number: 17 },
                { number: 18 },
                { number: 19 },
                { number: 20 },
                { number: 21 },
                { number: 22 },
                { number: 23 },
                { number: 24 },
                { number: 25 },
                { number: 26 },
                { number: 27 },
                { number: 28 }
            ]
        },
        {
            number: 15,
            tickets: [
                { number: 1 },
                { number: 2 },
                { number: 3 },
                { number: 4 },
                { number: 5 },
                { number: 6 },
                { number: 7 },
                { number: 8 },
                { number: 9 },
                { number: 10 },
                { number: 11 },
                { number: 12 },
                { number: 13 },
                { number: 14 },
                { number: 15 },
                { number: 16 },
                { number: 17 },
                { number: 18 },
                { number: 19 },
                { number: 20 },
                { number: 21 },
                { number: 22 },
                { number: 23 },
                { number: 24 },
                { number: 25 },
                { number: 26 },
                { number: 27 },
                { number: 28 }
            ]
        },
        {
            number: 16,
            tickets: [
                { number: 1 },
                { number: 2 },
                { number: 3 },
                { number: 4 },
                { number: 5 },
                { number: 6 },
                { number: 7 },
                { number: 8 },
                { number: 9 },
                { number: 10 },
                { number: 11 },
                { number: 12 },
                { number: 13 },
                { number: 14 },
                { number: 15 },
                { number: 16 },
                { number: 17 },
                { number: 18 },
                { number: 19 },
                { number: 20 },
                { number: 21 },
                { number: 22 },
                { number: 23 },
                { number: 24 },
                { number: 25 },
                { number: 26 },
                { number: 27 },
                { number: 28 }
            ]
        },
        {
            number: 17,
            tickets: [
                { number: 1 },
                { number: 2 },
                { number: 3 },
                { number: 4 },
                { number: 5 },
                { number: 6 },
                { number: 7 },
                { number: 8 },
                { number: 9 },
                { number: 10 },
                { number: 11 },
                { number: 12, priceRange: priceRange[0] },
                { number: 13, priceRange: priceRange[0] },
                { number: 14, priceRange: priceRange[0] },
                { number: 15, priceRange: priceRange[0] },
                { number: 16, priceRange: priceRange[0] },
                { number: 17 },
                { number: 18 },
                { number: 19 },
                { number: 20 },
                { number: 21 },
                { number: 22, priceRange: priceRange[0] },
                { number: 23, priceRange: priceRange[0] },
                { number: 24, priceRange: priceRange[0] },
                { number: 25, priceRange: priceRange[0] },
                { number: 26, priceRange: priceRange[0] },
                { number: 27, priceRange: priceRange[0] },
                { number: 28, priceRange: priceRange[0] }
            ]
        },
        {
            number: 18,
            tickets: [
                { number: 1 },
                { number: 2 },
                { number: 3 },
                { number: 4 },
                { number: 5 },
                { number: 6 },
                { number: 7 },
                { number: 8 },
                { number: 9 },
                { number: 10 },
                { number: 11 },
                { number: 12, priceRange: priceRange[0] },
                { number: 13, priceRange: priceRange[0] },
                { number: 14, priceRange: priceRange[0] },
                { number: 15, priceRange: priceRange[0] },
                { number: 16, priceRange: priceRange[0] },
                { number: 17 },
                { number: 18 },
                { number: 19 },
                { number: 20 },
                { number: 21 },
                { number: 22, priceRange: priceRange[0] },
                { number: 23, priceRange: priceRange[0] },
                { number: 24, priceRange: priceRange[0] },
                { number: 25, priceRange: priceRange[0] },
                { number: 26, priceRange: priceRange[0] },
                { number: 27, priceRange: priceRange[0] },
                { number: 28, priceRange: priceRange[0] }
            ]
        },
        {
            number: 19,
            tickets: [
                { number: 1 },
                { number: 2 },
                { number: 3 },
                { number: 4 },
                { number: 5 },
                { number: 6 },
                { number: 7 },
                { number: 8 },
                { number: 9 },
                { number: 10 },
                { number: 11 },
                { number: 12, priceRange: priceRange[0] },
                { number: 13, priceRange: priceRange[0] },
                { number: 14, priceRange: priceRange[0] },
                { number: 15, priceRange: priceRange[0] },
                { number: 16, priceRange: priceRange[0] },
                { number: 17 },
                { number: 18 },
                { number: 19 },
                { number: 20 },
                { number: 21 },
                { number: 22, priceRange: priceRange[0] },
                { number: 23, priceRange: priceRange[0] },
                { number: 24, priceRange: priceRange[0] },
                { number: 25, priceRange: priceRange[0] },
                { number: 26, priceRange: priceRange[0] },
                { number: 27, priceRange: priceRange[0] },
                { number: 28, priceRange: priceRange[0] }
            ]
        },
        {
            number: 20,
            tickets: [
                { number: 1 },
                { number: 2 },
                { number: 3 },
                { number: 4 },
                { number: 5 },
                { number: 6 },
                { number: 7 },
                { number: 8 },
                { number: 9 },
                { number: 10 },
                { number: 11 },
                { number: 12, priceRange: priceRange[0] },
                { number: 13, priceRange: priceRange[0] },
                { number: 14, priceRange: priceRange[0] },
                { number: 15, priceRange: priceRange[0] },
                { number: 16, priceRange: priceRange[0] },
                { number: 17 },
                { number: 18 },
                { number: 19 },
                { number: 20 },
                { number: 21 },
                { number: 22, priceRange: priceRange[0] },
                { number: 23, priceRange: priceRange[0] },
                { number: 24, priceRange: priceRange[0] },
                { number: 25, priceRange: priceRange[0] },
                { number: 26, priceRange: priceRange[0] },
                { number: 27, priceRange: priceRange[0] },
                { number: 28, priceRange: priceRange[0] }
            ]
        },
        {
            number: 21,
            tickets: [
                { number: 1 },
                { number: 2 },
                { number: 3 },
                { number: 4 },
                { number: 5 },
                { number: 6 },
                { number: 7 },
                { number: 8 },
                { number: 9 },
                { number: 10 },
                { number: 11 },
                { number: 12, priceRange: priceRange[0] },
                { number: 13, priceRange: priceRange[0] },
                { number: 14, priceRange: priceRange[0] },
                { number: 15, priceRange: priceRange[0] },
                { number: 16, priceRange: priceRange[0] },
                { number: 17 },
                { number: 18 },
                { number: 19 },
                { number: 20 },
                { number: 21 },
                { number: 22, priceRange: priceRange[0] },
                { number: 23, priceRange: priceRange[0] },
                { number: 24, priceRange: priceRange[0] },
                { number: 25, priceRange: priceRange[0] },
                { number: 26, priceRange: priceRange[0] },
                { number: 27, priceRange: priceRange[0] },
                { number: 28, priceRange: priceRange[0] }
            ]
        },
        {
            number: 22,
            tickets: [
                { number: 1 },
                { number: 2 },
                { number: 3 },
                { number: 4 },
                { number: 5 },
                { number: 6 },
                { number: 7 },
                { number: 8 },
                { number: 9 },
                { number: 10 },
                { number: 11 },
                { number: 12 },
                { number: 13, priceRange: priceRange[0] },
                { number: 14, priceRange: priceRange[0] },
                { number: 15, priceRange: priceRange[0] },
                { number: 16, priceRange: priceRange[0] },
                { number: 17 },
                { number: 18 },
                { number: 19 },
                { number: 20 },
                { number: 21 },
                { number: 22, priceRange: priceRange[0] },
                { number: 23, priceRange: priceRange[0] },
                { number: 24, priceRange: priceRange[0] },
                { number: 25, priceRange: priceRange[0] },
                { number: 26, priceRange: priceRange[0] },
                { number: 27, priceRange: priceRange[0] },
                { number: 28, priceRange: priceRange[0] }
            ]
        },
        {
            number: 23,
            tickets: [
                { number: 1 },
                { number: 2 },
                { number: 3 },
                { number: 4 },
                { number: 5 },
                { number: 6 },
                { number: 7 },
                { number: 8 },
                { number: 9 },
                { number: 10 },
                { number: 11 },
                { number: 12 },
                { number: 13 },
                { number: 14 },
                { number: 15 },
                { number: 16 },
                { number: 17 },
                { number: 18 },
                { number: 19 },
                { number: 20 },
                { number: 21 },
                { number: 22 },
                { number: 23 },
                { number: 24 },
                { number: 25 },
                { number: 26 },
                { number: 27 },
                { number: 28 }
            ]
        },
        {
            number: 24,
            tickets: [
                { number: 1 },
                { number: 2 },
                { number: 3 },
                { number: 4 },
                { number: 5 },
                { number: 6 },
                { number: 7 },
                { number: 8 },
                { number: 9 },
                { number: 10 },
                { number: 11 },
                { number: 12 },
                { number: 13 },
                { number: 14 },
                { number: 15 },
                { number: 16 },
                { number: 17 },
                { number: 18 },
                { number: 19 },
                { number: 20 },
                { number: 21 },
                { number: 22 },
                { number: 23 },
                { number: 24 },
                { number: 25 },
                { number: 26 },
                { number: 27 },
                { number: 28 }
            ]
        },
    ]
}