-- AlterTable
ALTER TABLE `Ticket` ADD COLUMN `venueId` INTEGER NULL;

-- AlterTable
ALTER TABLE `Venue` ADD COLUMN `active` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `address` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `noPlaces` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `start` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AddForeignKey
ALTER TABLE `Ticket` ADD CONSTRAINT `Ticket_venueId_fkey` FOREIGN KEY (`venueId`) REFERENCES `Venue`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
